name: Parse the .components directory
description: ""

inputs: {}

outputs:
  COMPONENTS:
    description: JSON map of components info
    value: ${{ steps.parse-infos.outputs.parsed }}

runs:
  using: composite
  steps:
    -
      shell: bash
      id: parse-infos
      env:
        SCRIPT_FILE: ${{ github.action_path }}/action.sh
      run: |
        # Parse components info

        echo "::group::Parsing components info"

        ALL_COMPONENTS_JSON=$("${SCRIPT_FILE}")

        printf '%s' "$ALL_COMPONENTS_JSON" | jq '.'

        echo "::endgroup::"

        echo "parsed=$ALL_COMPONENTS_JSON" >> "$GITHUB_OUTPUT"
        
