name: Parse the .components directory
description: ""

inputs: {}

outputs:
  info:
    description: JSON map of components info
    value: ${{ steps.parse-infos.outputs.info }}

runs:
  using: composite
  steps:
    -
      shell: bash
      id: parse-infos
      env:
        SCRIPT_FILE: ${{ github.action_path }}/action.sh
      run: |
        # Parse components info

        ALL_COMPONENTS_JSON=$("${SCRIPT_FILE}")
        echo "info=$ALL_COMPONENTS_JSON" | tee -a "$GITHUB_OUTPUT"
        
